# Generated by Django 4.1.7 on 2023-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autochton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('attributes', models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32)),
                ('dream', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('attributes', models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32)),
                ('player', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
