# Generated by Django 4.1.7 on 2023-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
