# Generated by Django 4.1.7 on 2023-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_autochton_rid_traveller_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='player',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
