# Generated by Django 4.1.7 on 2023-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_traveller_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='connaissances',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='autochton',
            name='draconiques',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='autochton',
            name='generales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='autochton',
            name='martiales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='autochton',
            name='paerticulieres',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='autochton',
            name='specialisees',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='connaissances',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='draconiques',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='generales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='martiales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='paerticulieres',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
        migrations.AddField(
            model_name='traveller',
            name='specialisees',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=32),
        ),
    ]
