# Generated by Django 4.1.7 on 2023-11-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_autochton_paerticulieres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='connaissances',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='draconiques',
            field=models.CharField(blank=True, default='0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='generales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='martiales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='particulieres',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='specialisees',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='connaissances',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='draconiques',
            field=models.CharField(blank=True, default='0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='generales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='martiales',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='particulieres',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='specialisees',
            field=models.CharField(blank=True, default='0 0 0 0 0 0 0 0 0 0', max_length=64),
        ),
    ]
