# Generated by Django 4.1.7 on 2023-11-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_autochton_connaissances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='secondary',
            field=models.CharField(blank=True, default='0 0 0 0', max_length=16),
        ),
        migrations.AddField(
            model_name='traveller',
            name='secondary',
            field=models.CharField(blank=True, default='0 0 0 0', max_length=16),
        ),
    ]
