# Generated by Django 4.1.7 on 2023-11-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_autochton_secondary_traveller_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autochton',
            name='secondary',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='secondary',
        ),
    ]
