# Generated by Django 4.1.7 on 2023-11-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_autochton_secondary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
