# Generated by Django 4.1.7 on 2023-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_autochton_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='martiales',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='martiales',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
