# Generated by Django 4.1.7 on 2023-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_autochton_martiales_alter_traveller_martiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='entrance',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='attributes',
            field=models.CharField(blank=True, default='3 3 3 3 3 3 3 3 3 3 3 3', max_length=32),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='attributes',
            field=models.CharField(blank=True, default='3 3 3 3 3 3 3 3 3 3 3 3', max_length=32),
        ),
    ]
