# Generated by Django 4.1.7 on 2023-11-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_autochton_entrance_traveller_entrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='randomize',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='randomize',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
