# Generated by Django 4.1.7 on 2023-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_autochton_updater_traveller_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='indice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='indice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
