# Generated by Django 4.1.7 on 2023-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_autochton_indice_traveller_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='equipe',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='autochton',
            name='groupe',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='autochton',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='equipe',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='groupe',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
