# Generated by Django 4.1.7 on 2023-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_autochton_equipe_autochton_groupe_autochton_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='birthhour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='birthhour',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
