# Generated by Django 4.1.7 on 2023-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_autochton_birthhour_traveller_birthhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='factions',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='factions',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
