# Generated by Django 4.1.7 on 2023-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_autochton_factions_traveller_factions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='connaissances',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='draconiques',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='generales',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='particulieres',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='autochton',
            name='specialisees',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='connaissances',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='draconiques',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='generales',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='particulieres',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='specialisees',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
