# Generated by Django 4.1.7 on 2023-11-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_autochton_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autochton',
            old_name='groupe',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='draconiques',
            new_name='skills_draconic',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='generales',
            new_name='skills_generic',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='connaissances',
            new_name='skills_knowledge',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='particulieres',
            new_name='skills_peculiar',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='specialisees',
            new_name='skills_specialized',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='martiales',
            new_name='skills_weapons',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='equipe',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='groupe',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='draconiques',
            new_name='skills_draconic',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='generales',
            new_name='skills_generic',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='connaissances',
            new_name='skills_knowledge',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='particulieres',
            new_name='skills_peculiar',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='specialisees',
            new_name='skills_specialized',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='martiales',
            new_name='skills_weapons',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='equipe',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='titre',
            new_name='title',
        ),
    ]
