# Generated by Django 4.1.7 on 2023-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_autochton_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('idcode', models.PositiveIntegerField(blank=True, default=0)),
                ('session_number', models.PositiveIntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
