# Generated by Django 4.1.7 on 2023-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_dream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='idcode',
        ),
        migrations.AddField(
            model_name='dream',
            name='rid',
            field=models.CharField(blank=True, default='xxx', max_length=256),
        ),
    ]
