# Generated by Django 4.1.7 on 2023-12-03 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_dream_idcode_dream_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='date_run',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
