# Generated by Django 4.1.7 on 2023-12-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.FloatField(blank=True, default=0.1),
        ),
    ]
