# Generated by Django 4.1.7 on 2023-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_equipment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='plus_dom_2m',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
