# Generated by Django 4.1.7 on 2023-12-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_equipment_plus_dom_2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='plus_dom',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='plus_dom_2m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
