# Generated by Django 4.1.7 on 2023-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_equipment_plus_dom_alter_equipment_plus_dom_2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='force_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
