# Generated by Django 4.1.7 on 2023-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_equipment_force_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='malus_armure',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='prot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
