# Generated by Django 4.1.7 on 2023-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_autochton_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
