# Generated by Django 4.1.7 on 2023-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_dream_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='autochton',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=160),
        ),
        migrations.AddField(
            model_name='autochton',
            name='is_female',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='autochton',
            name='is_lefty',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='autochton',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='traveller',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='traveller',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=160),
        ),
        migrations.AddField(
            model_name='traveller',
            name='is_female',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='is_lefty',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
    ]
