# Generated by Django 4.1.7 on 2023-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_autochton_age_autochton_height_autochton_is_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='place',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='place',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
