# Generated by Django 4.0 on 2023-12-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_equipment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['id']},
        ),
    ]
