# Generated by Django 4.0 on 2023-12-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_equipment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
