# Generated by Django 4.0 on 2024-01-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_equipment_options_alter_equipment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='indice_attributes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='autochton',
            name='indice_skills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='indice_attributes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='indice_skills',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
