# Generated by Django 4.0 on 2024-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_autochton_total_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='sre',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='sre',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
