# Generated by Django 4.0 on 2024-01-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_autochton_sre_traveller_sre'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='tre',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='tre',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
