# Generated by Django 4.0 on 2024-01-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_autochton_tre_traveller_tre'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='imc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='imc',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
