# Generated by Django 4.0 on 2024-01-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_autochton_imc_traveller_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='tai_guideline',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='traveller',
            name='tai_guideline',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
