# Generated by Django 4.0 on 2024-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_autochton_height_alter_traveller_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('rid', models.CharField(blank=True, default='xxx', max_length=256)),
                ('alternative_names', models.CharField(blank=True, default='', max_length=512)),
                ('casting_time', models.PositiveIntegerField(blank=True, default=1)),
                ('ground_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('hour_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('emanation_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('consistency_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('elemental_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('dps', models.PositiveIntegerField(blank=True, default=3)),
                ('diff', models.PositiveIntegerField(blank=True, choices=[(5, 'Très Facile'), (10, 'Facile'), (15, 'Moyenne'), (20, 'Difficile'), (25, 'Très Difficile')], default=15)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('duration', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('rid', models.CharField(blank=True, default='xxx', max_length=256)),
                ('alternative_names', models.CharField(blank=True, default='', max_length=512)),
                ('casting_time', models.PositiveIntegerField(blank=True, default=1)),
                ('ground_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('hour_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('emanation_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('consistency_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('elemental_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('dps', models.PositiveIntegerField(blank=True, default=3)),
                ('diff', models.PositiveIntegerField(blank=True, choices=[(5, 'Très Facile'), (10, 'Facile'), (15, 'Moyenne'), (20, 'Difficile'), (25, 'Très Difficile')], default=15)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('component_ground_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('component_hour_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('component_emanation_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('component_consistency_charge', models.PositiveIntegerField(blank=True, default=0)),
                ('component_elemental_charge', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
