# Generated by Django 4.0 on 2024-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_incantation_ritual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incantation',
            name='consistency_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Humeur'), (2, 'Vapeur'), (3, 'Fluide'), (4, 'Précipité'), (5, 'Congestion'), (6, 'Amas'), (7, 'Cristal')], default=0),
        ),
        migrations.AlterField(
            model_name='incantation',
            name='elemental_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Sanctuaire'), (2, 'Désert'), (3, 'Monts'), (4, 'Cité'), (5, 'Forêt'), (6, 'Plaine'), (7, 'Collines')], default=0),
        ),
        migrations.AlterField(
            model_name='incantation',
            name='emanation_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Ondée'), (2, 'Flux'), (3, 'Courant'), (4, 'Vague'), (5, 'Marée'), (6, 'Ras'), (7, 'Déferlante')], default=0),
        ),
        migrations.AlterField(
            model_name='incantation',
            name='ground_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Sanctuaire'), (2, 'Désert'), (3, 'Monts'), (4, 'Cité'), (5, 'Forêt'), (6, 'Plaine'), (7, 'Collines'), (8, 'Pont'), (9, 'Fleuve'), (10, 'Lac'), (11, 'Marais'), (12, 'Désolation'), (13, 'Gouffre'), (14, 'Nécropole')], default=0),
        ),
        migrations.AlterField(
            model_name='incantation',
            name='hour_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Vaisseau'), (2, 'Sirène'), (3, 'Faucon'), (4, 'Couronne'), (5, 'Dragon'), (6, 'Epées'), (7, 'Lyre'), (8, 'Serpent'), (9, 'Poisson-Acrobate'), (10, 'Araignée'), (11, 'Roseau'), (12, 'Château-Dormant')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='consistency_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Humeur'), (2, 'Vapeur'), (3, 'Fluide'), (4, 'Précipité'), (5, 'Congestion'), (6, 'Amas'), (7, 'Cristal')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='elemental_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Sanctuaire'), (2, 'Désert'), (3, 'Monts'), (4, 'Cité'), (5, 'Forêt'), (6, 'Plaine'), (7, 'Collines')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='emanation_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Ondée'), (2, 'Flux'), (3, 'Courant'), (4, 'Vague'), (5, 'Marée'), (6, 'Ras'), (7, 'Déferlante')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='ground_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Sanctuaire'), (2, 'Désert'), (3, 'Monts'), (4, 'Cité'), (5, 'Forêt'), (6, 'Plaine'), (7, 'Collines'), (8, 'Pont'), (9, 'Fleuve'), (10, 'Lac'), (11, 'Marais'), (12, 'Désolation'), (13, 'Gouffre'), (14, 'Nécropole')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='hour_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Vaisseau'), (2, 'Sirène'), (3, 'Faucon'), (4, 'Couronne'), (5, 'Dragon'), (6, 'Epées'), (7, 'Lyre'), (8, 'Serpent'), (9, 'Poisson-Acrobate'), (10, 'Araignée'), (11, 'Roseau'), (12, 'Château-Dormant')], default=0),
        ),
    ]
