# Generated by Django 4.0 on 2024-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_incantation_consistency_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incantation',
            name='elemental_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Eau'), (2, 'Feu'), (3, 'Terre'), (4, 'Air'), (5, 'Bois'), (6, 'Métal'), (7, 'Septième')], default=0),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='elemental_charge',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Eau'), (2, 'Feu'), (3, 'Terre'), (4, 'Air'), (5, 'Bois'), (6, 'Métal'), (7, 'Septième')], default=0),
        ),
    ]
