# Generated by Django 4.0 on 2024-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_incantation_elemental_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incantation',
            name='ref',
            field=models.CharField(blank=True, default='RDD 2nd p.', max_length=32),
        ),
        migrations.AddField(
            model_name='ritual',
            name='ref',
            field=models.CharField(blank=True, default='RDD 2nd p.', max_length=32),
        ),
    ]
