# Generated by Django 4.0 on 2024-01-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_incantation_ref_ritual_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='incantation',
            name='path',
            field=models.CharField(blank=True, default='Hypnos', max_length=32),
        ),
        migrations.AddField(
            model_name='ritual',
            name='path',
            field=models.CharField(blank=True, default='Hypnos', max_length=32),
        ),
    ]
