# Generated by Django 4.0 on 2024-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_spell_delete_incantation_delete_ritual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Incantation'), (2, 'Rituel')], default=0),
        ),
        migrations.AlterField(
            model_name='spell',
            name='path',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Hypnos'), (2, 'Oniros'), (3, 'Narcos'), (4, 'Thanatos'), (5, 'Morpheos')], default=0),
        ),
    ]
