# Generated by Django 4.0 on 2024-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_spell_category_alter_spell_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='path',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Génénrique'), (2, 'Hypnos'), (3, 'Oniros'), (4, 'Narcos'), (5, 'Thanatos'), (6, 'Morpheos')], default=0),
        ),
    ]
