# Generated by Django 4.0 on 2024-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_spell_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Incantation'), (2, 'Rituel')], default=0),
        ),
    ]
