# Generated by Django 4.0 on 2024-01-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_spell_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='original_casting_cost',
            field=models.CharField(blank=True, default='-', max_length=1024),
        ),
    ]
