# Generated by Django 4.0 on 2024-01-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_spell_roll_alter_spell_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.CharField(blank=True, default='-', max_length=64),
        ),
    ]
