# Generated by Django 4.0 on 2024-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_spell_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='aka',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='aka',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
