# Generated by Django 4.0 on 2024-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_autochton_aka_traveller_aka'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='gamers_team',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='gamers_team',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
