# Generated by Django 4.0 on 2024-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_autochton_gamers_team_traveller_gamers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='color',
            field=models.CharField(blank=True, default='#202020', max_length=9),
        ),
        migrations.AddField(
            model_name='traveller',
            name='color',
            field=models.CharField(blank=True, default='#202020', max_length=9),
        ),
    ]
