# Generated by Django 4.0 on 2024-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_autochton_color_traveller_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='updater',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='updater',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
    ]
