# Generated by Django 4.0 on 2024-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_autochton_prot_traveller_prot'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='gear',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='autochton',
            name='spells',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='traveller',
            name='destiny',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='gear',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='traveller',
            name='spells',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
