# Generated by Django 4.0 on 2024-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_autochton_gear_autochton_spells_traveller_destiny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
