# Generated by Django 4.0 on 2024-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_equipment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='materiaux',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
