# Generated by Django 4.0 on 2024-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_equipment_materiaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mod_att',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mod_dom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mod_ini',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
