# Generated by Django 4.0 on 2024-01-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_equipment_mod_att_equipment_mod_dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='special',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
