# Generated by Django 4.0 on 2024-01-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_equipment_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autochton',
            old_name='tre',
            new_name='fable',
        ),
        migrations.RenameField(
            model_name='autochton',
            old_name='sre',
            new_name='songe',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='tre',
            new_name='fable',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='sre',
            new_name='songe',
        ),
    ]
