# Generated by Django 4.0 on 2024-01-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_rename_tre_autochton_fable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autochton',
            old_name='fable',
            new_name='reve',
        ),
        migrations.RenameField(
            model_name='traveller',
            old_name='fable',
            new_name='reve',
        ),
    ]
