# Generated by Django 4.0 on 2024-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_rename_fable_autochton_reve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='spotlight',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
