# Generated by Django 4.0 on 2024-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_autochton_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='color',
            field=models.CharField(blank=True, default='#808080', max_length=9),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='color',
            field=models.CharField(blank=True, default='#808080', max_length=9),
        ),
    ]
