# Generated by Django 4.0 on 2024-02-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_spell_spell_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['-spell_ready', 'name']},
        ),
    ]
