# Generated by Django 4.0 on 2024-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_spell_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
