# Generated by Django 4.0 on 2024-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_autochton_priority_traveller_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('rid', models.CharField(blank=True, default='xxx', max_length=256)),
                ('equipment_match', models.CharField(blank=True, default='xxx', max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('price', models.FloatField(blank=True, default=0.1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
