# Generated by Django 4.0 on 2024-02-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_appartus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='dps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appartus',
            name='glance',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='appartus',
            name='inertia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appartus',
            name='mastery',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appartus',
            name='materials',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='appartus',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='appartus',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1000),
        ),
    ]
