# Generated by Django 4.0 on 2024-02-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_appartus_dps_appartus_glance_appartus_inertia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='scales',
            field=models.CharField(blank=True, default='e', max_length=256),
        ),
    ]
