# Generated by Django 4.0 on 2024-02-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_appartus_scales'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='mode_dmg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appartus',
            name='mode_init',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appartus',
            name='mode_touch',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
