# Generated by Django 4.0 on 2024-02-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_appartus_mode_dmg_appartus_mode_init_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartus',
            old_name='mode_dmg',
            new_name='mod_dmg',
        ),
        migrations.RenameField(
            model_name='appartus',
            old_name='mode_init',
            new_name='mod_init',
        ),
        migrations.RenameField(
            model_name='appartus',
            old_name='mode_touch',
            new_name='mod_touch',
        ),
    ]
