# Generated by Django 4.0 on 2024-03-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_spell_composantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='songe',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
