# Generated by Django 4.0 on 2024-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_dream_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='classe_engagement',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
