# Generated by Django 4.0 on 2024-03-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_equipment_classe_engagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Appartuses'},
        ),
    ]
