# Generated by Django 4.0 on 2024-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_appartus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='appartus',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='appartus',
            name='rules',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
