# Generated by Django 4.0 on 2024-03-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_appartus_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='charges',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
