# Generated by Django 4.0 on 2024-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_appartus_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='nameless',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
