# Generated by Django 4.0 on 2024-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_autochton_nameless'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ti',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Instantanné'), (1, 'Tour'), (2, 'Minute'), (3, 'Demi-Heure Draconique'), (4, 'Heure Draconique'), (5, 'Jour'), (6, 'Semaine')], default=0),
        ),
    ]
