# Generated by Django 4.0 on 2024-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_spell_ti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='category',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Incantation'), (2, 'Rituel'), (3, 'Pentacle')], default=0),
        ),
    ]
