# Generated by Django 4.0 on 2024-03-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_spell_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='power',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
