# Generated by Django 4.0 on 2024-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_spell_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='power',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
