# Generated by Django 4.0 on 2024-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_appartus_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='gems',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
