# Generated by Django 4.0 on 2024-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_autochton_team_color_traveller_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='figure',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='figure',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
