# Generated by Django 4.0 on 2024-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_autochton_figure_traveller_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='is_battle_ready',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='is_battle_ready',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
