# Generated by Django 4.0 on 2025-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_spell_consistency_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rid', models.CharField(blank=True, default='', max_length=256)),
                ('randomize', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('aka', models.CharField(blank=True, default='', max_length=256)),
                ('figure', models.CharField(blank=True, default='', max_length=256)),
                ('group', models.CharField(blank=True, default='', max_length=256)),
                ('team', models.CharField(blank=True, default='', max_length=256)),
                ('factions', models.CharField(blank=True, default='', max_length=256)),
                ('entrance', models.CharField(blank=True, default='', max_length=256)),
                ('birthhour', models.IntegerField(blank=True, default=0)),
                ('is_female', models.BooleanField(blank=True, default=False)),
                ('is_lefty', models.BooleanField(blank=True, default=False)),
                ('is_battle_ready', models.BooleanField(blank=True, default=False)),
                ('age', models.PositiveIntegerField(blank=True, default=20)),
                ('height', models.PositiveIntegerField(blank=True, default=10)),
                ('weight', models.PositiveIntegerField(blank=True, default=50)),
                ('songe', models.IntegerField(blank=True, default=0)),
                ('reve', models.IntegerField(blank=True, default=0)),
                ('prot', models.IntegerField(blank=True, default=0)),
                ('color', models.CharField(blank=True, default='#808080', max_length=9)),
                ('team_color', models.CharField(blank=True, default='', max_length=10)),
                ('gamers_team', models.BooleanField(blank=True, default=False)),
                ('gear', models.TextField(blank=True, default='', max_length=1024)),
                ('spells', models.TextField(blank=True, default='', max_length=1024)),
                ('imc', models.FloatField(blank=True, default=0)),
                ('place', models.CharField(blank=True, default='', max_length=256)),
                ('attributes', models.CharField(blank=True, default='', max_length=64)),
                ('skills_weapons', models.CharField(blank=True, default='', max_length=128)),
                ('skills_generic', models.CharField(blank=True, default='', max_length=128)),
                ('skills_peculiar', models.CharField(blank=True, default='', max_length=128)),
                ('skills_specialized', models.CharField(blank=True, default='', max_length=128)),
                ('skills_knowledge', models.CharField(blank=True, default='', max_length=128)),
                ('skills_draconic', models.CharField(blank=True, default='', max_length=128)),
                ('indice', models.IntegerField(blank=True, default=0)),
                ('indice_attributes', models.IntegerField(blank=True, default=0)),
                ('indice_skills', models.IntegerField(blank=True, default=0)),
                ('tai_guideline', models.CharField(blank=True, default='', max_length=128)),
                ('total_attributes', models.IntegerField(blank=True, default=0)),
                ('updater', models.TextField(blank=True, default='{}', max_length=8192)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(blank=True, choices=[('ANI', 'Animal'), ('HUM', 'Humanoïde'), ('NIC', 'Créature de Cauchemard'), ('NIE', 'Entité de Cauchemard'), ('FAE', 'Fée'), ('ELE', 'Elémentaire')], default='ANI', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
