# Generated by Django 4.0 on 2025-12-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_creature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='type',
            new_name='creature_type',
        ),
    ]
