# Generated by Django 4.0 on 2025-12-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_rename_type_creature_creature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='player',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='creature',
            name='player',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
