# Generated by Django 4.0 on 2025-12-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_autochton_player_creature_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autochton',
            name='player',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='player',
        ),
    ]
