# Generated by Django 4.0 on 2025-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_remove_autochton_player_remove_creature_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('adventure', models.CharField(blank=True, default='', max_length=128)),
                ('rids', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
