# Generated by Django 4.0 on 2025-12-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='total_skills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='total_skills',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='traveller',
            name='total_skills',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
