# Generated by Django 4.0 on 2025-12-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_autochton_total_skills_creature_total_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='creature_type',
            field=models.CharField(blank=True, choices=[('ANI', 'Animal'), ('HUM', 'Humanoïde'), ('NIC', 'Créature de Cauchemard'), ('NIE', 'Entité de Cauchemard'), ('FAE', 'Fée'), ('ELE', 'Elémentaire'), ('ONI', 'Oniride')], default='ANI', max_length=3),
        ),
    ]
