# Generated by Django 4.0 on 2025-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_alter_creature_creature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
