# Generated by Django 4.0 on 2025-12-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_spell_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartus',
            name='code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
