# Generated by Django 4.0 on 2026-02-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_appartus_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(blank=True, default='', max_length=4)),
                ('team', models.CharField(blank=True, default='808080', max_length=16)),
                ('_data', models.TextField(blank=True, default='{}', max_length=2048)),
            ],
        ),
    ]
