# Generated by Django 4.0 on 2026-02-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_contestant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
