# Generated by Django 4.0 on 2026-02-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_alter_contestant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='fat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='vie',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
