# Generated by Django 4.0 on 2026-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_contestant_fat_contestant_vie'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='chosen_diff',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='contestant',
            name='handicap',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='two_handed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
