# Generated by Django 4.0 on 2026-02-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_contestant_chosen_diff_contestant_handicap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='klass',
            field=models.CharField(blank=True, default='Character', max_length=16),
        ),
        migrations.AddField(
            model_name='creature',
            name='klass',
            field=models.CharField(blank=True, default='Character', max_length=16),
        ),
        migrations.AddField(
            model_name='traveller',
            name='klass',
            field=models.CharField(blank=True, default='Character', max_length=16),
        ),
    ]
