# Generated by Django 4.0 on 2026-02-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_autochton_klass_creature_klass_traveller_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256)),
                ('_config', models.TextField(blank=True, default='{}', max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='combat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.combat'),
        ),
    ]
