# Generated by Django 4.0 on 2026-02-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_combat_contestant_combat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=0)),
                ('active_round', models.BooleanField(blank=True, default=False)),
                ('is_over', models.BooleanField(blank=True, default=False)),
                ('combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.combat')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
