# Generated by Django 4.0 on 2026-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_combatround'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='characters_list_str',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
