# Generated by Django 4.0 on 2026-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_combat_characters_list_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combat',
            old_name='characters_list_str',
            new_name='blue_team_str',
        ),
        migrations.AddField(
            model_name='combat',
            name='red_team_str',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
