# Generated by Django 4.0 on 2026-02-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_rename_characters_list_str_combat_blue_team_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='is_current',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='combat',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
