# Generated by Django 4.0 on 2026-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_combat_is_current_alter_combat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
