# Generated by Django 4.0 on 2026-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_alter_contestant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='team',
            field=models.CharField(blank=True, default='white', max_length=16),
        ),
    ]
