# Generated by Django 4.0 on 2026-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_alter_contestant_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='blue_contestants_str',
            field=models.TextField(blank=True, default='[]', max_length=2048),
        ),
        migrations.AddField(
            model_name='combat',
            name='red_contestants_str',
            field=models.TextField(blank=True, default='[]', max_length=2048),
        ),
    ]
