# Generated by Django 4.0 on 2026-02-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_combat_blue_contestants_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='source_rid',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='combat',
            name='blue_contestants_str',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='combat',
            name='red_contestants_str',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
