# Generated by Django 4.0 on 2026-02-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_contestant_source_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='rid',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
