# Generated by Django 4.0 on 2026-02-12 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_contestant_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='code',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='team',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='combat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.combat'),
        )
    ]
