# Generated by Django 4.0 on 2026-02-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_remove_contestant_code_remove_contestant_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='rid',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
