# Generated by Django 4.0 on 2026-02-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_alter_contestant_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='blue_real_rids',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='combat',
            name='red_real_rids',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
