# Generated by Django 4.0 on 2026-02-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_combat_blue_real_rids_combat_red_real_rids'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='current_round',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
