# Generated by Django 4.0 on 2026-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_combat_current_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatround',
            name='inits',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='contestant',
            name='last_initiative',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
