# Generated by Django 4.0 on 2026-02-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_combatround_inits_contestant_last_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatround',
            name='combat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_rounds', to='main.combat'),
        ),
    ]
