# Generated by Django 4.0 on 2026-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_alter_combatround_combat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_dead',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_out',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
