# Generated by Django 4.0 on 2026-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_contestant_is_dead_contestant_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_temporary',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
