# Generated by Django 4.0 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_contestant_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='avoidance',
            field=models.CharField(blank=True, default='esquive arme', max_length=256),
        ),
    ]
