# Generated by Django 4.0 on 2026-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_contestant_avoidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='fatigue_line',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='avoidance',
            field=models.CharField(blank=True, default='E A', max_length=256),
        ),
    ]
