# Generated by Django 4.0 on 2026-02-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_contestant_fatigue_line_alter_contestant_avoidance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='combat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challengers', to='main.combat'),
        ),
    ]
