# Generated by Django 4.0 on 2026-02-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_alter_contestant_combat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='is_temporary',
        ),
    ]
