# Generated by Django 4.0 on 2026-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_remove_contestant_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='personal_color',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='contestant',
            name='team_color',
            field=models.CharField(blank=True, default='#808080', max_length=7),
        ),
    ]
