# Generated by Django 4.0 on 2026-02-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0142_contestant_personal_color_contestant_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='damage_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
