# Generated by Django 4.0 on 2026-02-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_contestant_damage_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='foe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contestant'),
        ),
    ]
