# Generated by Django 4.0 on 2026-02-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0144_contestant_foe'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='special_effect_damage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='special_effect_defense_margin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='special_effect_initiative',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='contestant',
            name='special_effect_loc',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
