# Generated by Django 4.0 on 2026-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0145_contestant_special_effect_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
