# Generated by Django 4.0 on 2026-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_combat_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combat',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
