# Generated by Django 4.0 on 2026-02-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0148_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='protection_map',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='creature',
            name='protection_map',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='traveller',
            name='protection_map',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
