# Generated by Django 4.0 on 2026-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_autochton_protection_map_creature_protection_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0 C-0 AS-0 AW-0 LS-0 LW-0', max_length=256),
        ),
        migrations.AlterField(
            model_name='creature',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0 C-0 AS-0 AW-0 LS-0 LW-0', max_length=256),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0 C-0 AS-0 AW-0 LS-0 LW-0', max_length=256),
        ),
    ]
