# Generated by Django 4.0 on 2026-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_alter_autochton_protection_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X AS-0-X AW-0-X LS-0-X LW-0-X', max_length=256),
        ),
        migrations.AlterField(
            model_name='creature',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X AS-0-X AW-0-X LS-0-X LW-0-X', max_length=256),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X AS-0-X AW-0-X LS-0-X LW-0-X', max_length=256),
        ),
    ]
