# Generated by Django 4.0 on 2026-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_alter_autochton_protection_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='similitude',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
