# Generated by Django 4.0 on 2026-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_equipment_similitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='skill_match',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
