# Generated by Django 4.0 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_alter_equipment_skill_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='can_be_thrown',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='enc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
