# Generated by Django 4.0 on 2026-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_equipment_can_be_thrown_alter_equipment_enc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='bug_list',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='creature',
            name='bug_list',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='traveller',
            name='bug_list',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
