# Generated by Django 4.0 on 2026-02-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_autochton_bug_list_creature_bug_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='combat_style',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='contestant',
            name='combat_style_options',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
