# Generated by Django 4.0 on 2026-02-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_contestant_combat_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='number_of_foes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
