# Generated by Django 4.0 on 2026-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_contestant_number_of_foes'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
