# Generated by Django 4.0 on 2026-03-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_combat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='team',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
