# Generated by Django 4.0 on 2026-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_contestant_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
