# Generated by Django 6.0.6 on 2026-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_contestant_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='related_skill',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
