# Generated by Django 6.0.6 on 2026-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_alter_equipment_related_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='pentacle_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
