# Generated by Django 6.0.6 on 2026-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0163_spell_pentacle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='charge',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
