# Generated by Django 6.0.6 on 2026-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_spell_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='resistance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
