# Generated by Django 6.0.6 on 2026-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0165_equipment_resistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='famous_high_dreamers',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
