# Generated by Django 6.0.6 on 2026-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_spell_famous_high_dreamers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='path',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '-'), (1, 'Générique'), (2, 'Hypnos'), (3, 'Oniros'), (4, 'Narcos'), (5, 'Thanatos'), (6, 'Morphos')], default=0),
        ),
    ]
