# Generated by Django 6.0.6 on 2026-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0168_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
