# Generated by Django 6.0.6 on 2026-08-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0169_dream_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
