# Generated by Django 6.0.6 on 2026-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0170_alter_dream_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='population',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
