# Generated by Django 6.0.6 on 2026-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0172_alter_autochton_updater_alter_creature_updater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='updater',
            field=models.TextField(blank=True, default='{}', max_length=10240),
        ),
        migrations.AlterField(
            model_name='creature',
            name='updater',
            field=models.TextField(blank=True, default='{}', max_length=10240),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='updater',
            field=models.TextField(blank=True, default='{}', max_length=10240),
        ),
    ]
