# Generated by Django 6.0.6 on 2026-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_alter_autochton_updater_alter_creature_updater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='is_storyteller',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
