# Generated by Django 6.0.6 on 2026-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_traveller_is_storyteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='fallback',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, '1 charge / Echec'), (2, '3 charges / Notable')], default=0),
        ),
    ]
