# Generated by Django 6.0.6 on 2026-08-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0175_spell_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='fallback',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'une charge / Echec'), (2, 'toutes les charges / Notable')], default=0),
        ),
    ]
