# Generated by Django 6.0.6 on 2026-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_alter_spell_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='power_boost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
