# Generated by Django 6.0.6 on 2026-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0177_spell_power_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='diff',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 'Très Facile'), (10, 'Facile'), (15, 'Moyenne'), (20, 'Difficile'), (25, 'Très Difficile'), (30, 'Mythique'), (35, 'Légendaire')], default=15),
        ),
    ]
