# Generated by Django 6.0.6 on 2026-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_alter_spell_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='avoid_original_cost',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
