# Generated by Django 6.0.7 on 2026-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_spell_avoid_original_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='duration',
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_duration',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Immédiat'), (1, 'Tour'), (2, 'Tours'), (3, 'Minute'), (4, 'Minutes'), (5, 'HD'), (6, 'PHN'), (7, 'Semaine'), (8, 'Mois'), (9, 'Année'), (10, 'Décade'), (11, 'Permanent')], default=0),
        ),
        migrations.AlterField(
            model_name='spell',
            name='ti',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Instantané'), (1, 'Tour'), (2, 'Minute'), (3, 'Demi-heure Draconique'), (4, 'Heure Draconique'), (5, 'Jour'), (6, 'Semaine')], default=0),
        ),
    ]
