# Generated by Django 6.0.7 on 2026-08-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0180_remove_spell_duration_spell_spell_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='spell_duration',
            new_name='duration',
        ),
    ]
