# Generated by Django 6.0.7 on 2026-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0181_rename_spell_duration_spell_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='area',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'HR'), (2, 'VOL mètres')], default=0),
        ),
    ]
