# Generated by Django 6.0.7 on 2026-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0182_spell_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='range',
            new_name='toto',
        ),
        migrations.AddField(
            model_name='spell',
            name='range2',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'HR'), (2, 'Toucher'), (3, 'EMP mètres'), (4, 'EMPx2 mètres'), (5, 'EMPx4 mètres'), (6, 'EMPx6 mètres'), (7, 'EMPx10 mètres')], default=0),
        ),
    ]
