# Generated by Django 6.0.7 on 2026-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0183_rename_range_spell_toto_spell_range2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='range2',
            new_name='range',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='toto',
        ),
    ]
