# Generated by Django 6.0.7 on 2026-08-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0184_rename_range2_spell_range_remove_spell_toto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='area',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'HR'), (2, 'VOL m')], default=0),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'HR'), (2, 'Toucher'), (3, 'EMP m'), (4, 'EMPx2 m'), (5, 'EMPx4 m'), (6, 'EMPx6 m'), (7, 'EMPx10 m')], default=0),
        ),
    ]
