# Generated by Django 6.0.7 on 2026-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0185_alter_spell_area_alter_spell_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='autochton',
            name='is_nameless',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='creature',
            name='is_nameless',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='traveller',
            name='is_nameless',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
