# Generated by Django 6.0.7 on 2026-08-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0186_autochton_is_nameless_creature_is_nameless_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autochton',
            name='is_nameless',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='is_nameless',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='is_nameless',
        ),
    ]
