# Generated by Django 6.0.7 on 2026-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0187_remove_autochton_is_nameless_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autochton',
            name='dream',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
    ]
