# Generated by Django 6.0.7 on 2026-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0188_alter_autochton_dream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='creature_type',
        ),
        migrations.AddField(
            model_name='creature',
            name='creature_type2',
            field=models.CharField(blank=True, choices=[(0, 'Animal'), (1, 'Humanoïde'), (2, 'Créature de Cauchemard'), (3, 'Entité de Cauchemard'), (4, 'Fée'), (5, 'Elémentaire'), (6, 'Oniride')], default=0, max_length=3),
        ),
    ]
