# Generated by Django 6.0.7 on 2026-08-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0189_remove_creature_creature_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='creature_type2',
            new_name='creature_type',
        ),
    ]
