# Generated by Django 6.0.7 on 2026-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0190_rename_creature_type2_creature_creature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='creature_type',
            field=models.CharField(blank=True, choices=[(0, 'Animal'), (1, 'Humanoïde'), (2, 'Créature de Cauchemard'), (3, 'Entité de Cauchemard'), (4, 'Fée'), (5, 'Elémentaire'), (6, 'Oniride'), (7, 'Créature fabulause')], default=0, max_length=3),
        ),
    ]
