# Generated by Django 6.0.7 on 2026-08-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0194_alter_creature_creature_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autochton',
            new_name='Nativo',
        ),
    ]
