# Generated by Django 6.0.7 on 2026-08-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0195_rename_autochton_nativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traveller',
            new_name='Viaggiatore',
        ),
        migrations.AlterModelOptions(
            name='nativo',
            options={'verbose_name': 'Nativo', 'verbose_name_plural': 'Nativi'},
        ),
        migrations.AlterModelOptions(
            name='viaggiatore',
            options={'verbose_name': 'Viaggiatore', 'verbose_name_plural': 'Viaggiatori'},
        ),
    ]
