# Generated by Django 6.0.7 on 2026-08-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0196_rename_traveller_viaggiatore_alter_nativo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spell',
            new_name='Incantessimo',
        ),
        migrations.AlterModelOptions(
            name='incantessimo',
            options={'ordering': ['-spell_ready', 'name'], 'verbose_name': 'Incantessimo', 'verbose_name_plural': 'Incantessimi'},
        ),
    ]
