# Generated by Django 6.0.7 on 2026-08-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0197_rename_spell_incantessimo_alter_incantessimo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'verbose_name': 'Creatura', 'verbose_name_plural': 'Creature'},
        ),
    ]
