# Generated by Django 6.0.7 on 2026-08-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0198_alter_creature_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creature',
            new_name='Creatura',
        ),
    ]
