# Generated by Django 6.0.7 on 2026-08-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0199_rename_creature_creatura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appartus',
            new_name='Artefatto',
        ),
        migrations.AlterModelOptions(
            name='artefatto',
            options={'ordering': ['name'], 'verbose_name': 'Artefatto', 'verbose_name_plural': 'Artefatti'},
        ),
    ]
