# Generated by Django 6.0.7 on 2026-08-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_rename_appartus_artefatto_alter_artefatto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='stress_acquired',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='stress_remaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='stress_used',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='travel_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='stress_acquired',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='stress_remaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='stress_used',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='travel_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='stress_acquired',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='stress_remaining',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='stress_used',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='travel_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
