# Generated by Django 6.0.7 on 2026-08-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0201_creatura_stress_acquired_creatura_stress_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incantessimo',
            name='ti',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Instantané'), (1, 'Tour'), (2, 'Minute'), (3, 'Demi HD'), (4, 'HD'), (5, 'Jour'), (6, 'Semaine')], default=0),
        ),
    ]
