# Generated by Django 6.0.7 on 2026-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_alter_incantessimo_ti'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='nativo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
