# Generated by Django 6.0.7 on 2026-08-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0203_creatura_description_nativo_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dream',
            new_name='Sogno',
        ),
    ]
