# Generated by Django 6.0.7 on 2026-08-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_rename_dream_sogno'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='nativo',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
