# Generated by Django 6.0.7 on 2026-08-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0205_creatura_secondaries_nativo_secondaries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatura',
            old_name='reve',
            new_name='REV',
        ),
        migrations.RenameField(
            model_name='creatura',
            old_name='songe',
            new_name='SON',
        ),
        migrations.RenameField(
            model_name='nativo',
            old_name='reve',
            new_name='REV',
        ),
        migrations.RenameField(
            model_name='nativo',
            old_name='songe',
            new_name='SON',
        ),
        migrations.RenameField(
            model_name='viaggiatore',
            old_name='reve',
            new_name='REV',
        ),
        migrations.RenameField(
            model_name='viaggiatore',
            old_name='songe',
            new_name='SON',
        ),
        migrations.AddField(
            model_name='creatura',
            name='ENC',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='FAB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='FAT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='IMP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='RES',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='SUS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='VIE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='ENC',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='FAB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='FAT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='IMP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='RES',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='SUS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='VIE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='ENC',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='FAB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='FAT',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='IMP',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='RES',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='SUS',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='VIE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='creatura',
            name='attributes',
            field=models.CharField(blank=True, default='3 3 3 3 3 3 3 3 3 3 3 3', max_length=64),
        ),
        migrations.AlterField(
            model_name='creatura',
            name='secondaries',
            field=models.CharField(blank=True, default='0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='attributes',
            field=models.CharField(blank=True, default='3 3 3 3 3 3 3 3 3 3 3 3', max_length=64),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='secondaries',
            field=models.CharField(blank=True, default='0 0 0 0', max_length=64),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='attributes',
            field=models.CharField(blank=True, default='3 3 3 3 3 3 3 3 3 3 3 3', max_length=64),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='secondaries',
            field=models.CharField(blank=True, default='0 0 0 0', max_length=64),
        ),
    ]
