# Generated by Django 6.0.7 on 2026-08-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0206_rename_reve_creatura_rev_rename_songe_creatura_son_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatura',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='nativo',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='viaggiatore',
            name='updater',
        ),
    ]
