# Generated by Django 6.0.7 on 2026-08-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0207_remove_creatura_updater_remove_nativo_updater_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='malus_armure',
            new_name='malus_agi',
        ),
    ]
