# Generated by Django 6.0.7 on 2026-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0208_rename_malus_armure_equipment_malus_agi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='malus_agi',
            new_name='malus_AGI',
        ),
        migrations.AddField(
            model_name='equipment',
            name='malus_DEX',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='malus_OUI',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='malus_VUE',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
