# Generated by Django 6.0.7 on 2026-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0209_rename_malus_agi_equipment_malus_agi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='malus_AGI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='malus_DEX',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='malus_OUI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='creatura',
            name='malus_VUE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='malus_AGI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='malus_DEX',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='malus_OUI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='malus_VUE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='malus_AGI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='malus_DEX',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='malus_OUI',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='malus_VUE',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
