# Generated by Django 6.0.7 on 2026-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0210_creatura_malus_agi_creatura_malus_dex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='range',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
