# Generated by Django 6.0.7 on 2026-08-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0211_equipment_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatura',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='creatura',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='attributes',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='secondaries',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
