# Generated by Django 6.0.8 on 2026-08-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0212_alter_creatura_attributes_alter_creatura_secondaries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatura',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X A-0-X B-0-X L-0-X M-0-X', max_length=256),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X A-0-X B-0-X L-0-X M-0-X', max_length=256),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='protection_map',
            field=models.CharField(blank=True, default='H-0-X C-0-X A-0-X B-0-X L-0-X M-0-X', max_length=256),
        ),
    ]
