# Generated by Django 6.0.8 on 2026-08-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0213_alter_creatura_protection_map_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Oggetto',
        ),
    ]
