# Generated by Django 6.0.8 on 2026-08-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0215_oggetto_category2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oggetto',
            options={'ordering': ['category2'], 'verbose_name': 'Oggetto', 'verbose_name_plural': 'Oggetti'},
        ),
        migrations.RemoveField(
            model_name='oggetto',
            name='category',
        ),
    ]
