# Generated by Django 6.0.8 on 2026-08-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0216_alter_oggetto_options_remove_oggetto_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oggetto',
            options={'ordering': ['category'], 'verbose_name': 'Oggetto', 'verbose_name_plural': 'Oggetti'},
        ),
        migrations.RenameField(
            model_name='oggetto',
            old_name='category2',
            new_name='category',
        ),
    ]
