# Generated by Django 6.0.8 on 2026-08-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0217_alter_oggetto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='category',
            field=models.IntegerField(choices=[(1, 'n/a'), (2, 'Cuirs & Bagages'), (3, 'Jute, Fils & Cordes'), (4, 'Laine & lin'), (5, 'Velours & Soies'), (6, 'Feux'), (7, 'Poterie, Cuisine'), (8, 'Outillage'), (9, 'Soins'), (10, 'Ecriture'), (11, 'Jouer'), (12, 'Locomotion'), (13, 'Sustentation'), (14, 'Herbes de Soins'), (15, 'Herbes Diverses'), (16, 'Remèdes & Antidotes'), (17, 'Sels Alchimiques'), (18, 'Armes de Mêlée'), (19, 'Armes de Tir'), (20, 'Armes de Lancer'), (21, 'Armures'), (22, 'Armes Naturelles'), (23, 'Gemmes & Joyaux')], default=1),
        ),
    ]
