# Generated by Django 6.0.8 on 2026-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0218_alter_oggetto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='quality',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
