# Generated by Django 6.0.8 on 2026-09-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0219_oggetto_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oggetto',
            old_name='classe_engagement',
            new_name='engagement',
        ),
    ]
