# Generated by Django 6.0.8 on 2026-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0220_rename_classe_engagement_oggetto_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='maneuver',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
