# Generated by Django 6.0.8 on 2026-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0221_oggetto_maneuver'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
        migrations.AddField(
            model_name='nativo',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
    ]
