# Generated by Django 6.0.8 on 2026-09-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0222_creatura_skills_map_str_nativo_skills_map_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatura',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='creatura',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=150),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
