# Generated by Django 6.0.8 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0223_alter_creatura_height_alter_creatura_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatura',
            name='randomize',
        ),
        migrations.RemoveField(
            model_name='nativo',
            name='randomize',
        ),
        migrations.RemoveField(
            model_name='viaggiatore',
            name='randomize',
        ),
        migrations.AlterField(
            model_name='creatura',
            name='entrance',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='entrance',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='entrance',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
