# Generated by Django 6.0.8 on 2026-09-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0224_remove_creatura_randomize_remove_nativo_randomize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='skill_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='nativo',
            name='skill_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='skill_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
