# Generated by Django 6.0.8 on 2026-09-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0225_creatura_skill_creation_ok_nativo_skill_creation_ok_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatura',
            old_name='skill_creation_ok',
            new_name='skills_creation_ok',
        ),
        migrations.RenameField(
            model_name='nativo',
            old_name='skill_creation_ok',
            new_name='skills_creation_ok',
        ),
        migrations.RenameField(
            model_name='viaggiatore',
            old_name='skill_creation_ok',
            new_name='skills_creation_ok',
        ),
    ]
