# Generated by Django 6.0.8 on 2026-09-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0226_rename_skill_creation_ok_creatura_skills_creation_ok_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sogno',
            options={'verbose_name_plural': 'Sogni'},
        ),
    ]
