# Generated by Django 6.0.8 on 2026-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0227_alter_sogno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogno',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
