# Generated by Django 6.0.8 on 2026-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0228_sogno_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sogno',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
