# Generated by Django 6.0.8 on 2026-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0229_alter_sogno_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogno',
            name='creature',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sogno',
            name='nativi',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sogno',
            name='viaggiatori',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
