# Generated by Django 6.0.8 on 2026-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0230_sogno_creature_sogno_nativi_sogno_viaggiatori'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
        migrations.AddField(
            model_name='nativo',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
    ]
