# Generated by Django 6.0.8 on 2026-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0231_creatura_sogni_nativo_sogni_viaggiatore_sogni'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatto',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
        migrations.AddField(
            model_name='incantessimo',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='sogni',
            field=models.CharField(blank=True, default='DEF', max_length=256),
        ),
    ]
