# Generated by Django 6.0.8 on 2026-09-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0232_artefatto_sogni_incantessimo_sogni_oggetto_sogni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sogno',
            old_name='session_number',
            new_name='sort_order',
        ),
    ]
