# Generated by Django 6.0.8 on 2026-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0233_rename_session_number_sogno_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='attributes_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='nativo',
            name='attributes_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='attributes_creation_ok',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
