# Generated by Django 6.0.8 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0234_creatura_attributes_creation_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='pure_skills_total',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='nativo',
            name='pure_skills_total',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='pure_skills_total',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
