# Generated by Django 6.0.8 on 2026-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0235_creatura_pure_skills_total_nativo_pure_skills_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
        migrations.AddField(
            model_name='nativo',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=2048),
        ),
    ]
