# Generated by Django 6.0.8 on 2026-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0236_creatura_archetype_str_nativo_archetype_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatura',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='creatura',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='archetype_str',
            field=models.TextField(blank=True, default='{}', max_length=4096),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=8192),
        ),
    ]
