# Generated by Django 6.0.8 on 2026-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0237_alter_creatura_archetype_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='old_creation_attributes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='nativo',
            name='old_creation_attributes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='old_creation_attributes',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
