# Generated by Django 6.0.8 on 2026-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0238_creatura_old_creation_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='imc_boost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='nativo',
            name='imc_boost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='imc_boost',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
