# Generated by Django 6.0.8 on 2026-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0239_creatura_imc_boost_nativo_imc_boost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatura',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=12288),
        ),
        migrations.AlterField(
            model_name='nativo',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=12288),
        ),
        migrations.AlterField(
            model_name='viaggiatore',
            name='skills_map_str',
            field=models.TextField(blank=True, default='{}', max_length=12288),
        ),
    ]
