# Generated by Django 6.0.8 on 2026-09-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0240_alter_creatura_skills_map_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefatto',
            name='code',
        ),
    ]
