# Generated by Django 6.0.8 on 2026-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0241_remove_artefatto_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatto',
            name='equipment_code',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
