# Generated by Django 6.0.8 on 2026-09-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0242_artefatto_equipment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='mod_man',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
