# Generated by Django 6.0.8 on 2026-09-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0243_oggetto_mod_man'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefatto',
            old_name='mod_touch',
            new_name='mod_att',
        ),
        migrations.RenameField(
            model_name='artefatto',
            old_name='mod_init',
            new_name='mod_ini',
        ),
    ]
