# Generated by Django 6.0.8 on 2026-09-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0244_rename_mod_touch_artefatto_mod_att_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oggetto',
            name='mod_man',
        ),
    ]
