# Generated by Django 6.0.8 on 2026-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0245_remove_oggetto_mod_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='real_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
