# Generated by Django 6.0.8 on 2026-09-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0246_oggetto_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='mod_adjust',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='real_mod_adjust',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
