# Generated by Django 6.0.8 on 2026-09-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0247_oggetto_mod_adjust_oggetto_real_mod_adjust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefatto',
            old_name='mod_att',
            new_name='mod_man',
        ),
    ]
