# Generated by Django 6.0.8 on 2026-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0248_rename_mod_att_artefatto_mod_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefatto',
            name='gems',
        ),
        migrations.AddField(
            model_name='artefatto',
            name='gems_str',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
