# Generated by Django 6.0.8 on 2026-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0249_remove_artefatto_gems_artefatto_gems_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='color',
            field=models.CharField(blank=True, default='#808080ff', max_length=9),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='max_purity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='max_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='min_purity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='oggetto',
            name='min_size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
