# Generated by Django 6.0.8 on 2026-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0250_oggetto_color_oggetto_max_purity_oggetto_max_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='max_purity',
            field=models.IntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='max_size',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='min_purity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='min_size',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
