# Generated by Django 6.0.8 on 2026-09-20 09:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0251_alter_oggetto_max_purity_alter_oggetto_max_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='color',
            field=colorfield.fields.ColorField(default='#808080ff', image_field=None, max_length=25, samples=None),
        ),
    ]
