# Generated by Django 6.0.8 on 2026-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0252_alter_oggetto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='gcode',
            field=models.CharField(blank=True, default='xxx', max_length=3),
        ),
    ]
