# Generated by Django 6.0.8 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0253_oggetto_gcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefatto',
            name='period',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Unique'), (1, 'Par Tour'), (2, 'Par HD'), (3, 'Par Jour')], default=0),
        ),
    ]
