# Generated by Django 6.0.8 on 2026-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0254_artefatto_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefatto',
            name='dps',
        ),
        migrations.AddField(
            model_name='artefatto',
            name='pdr',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
