# Generated by Django 6.0.8 on 2026-09-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0255_remove_artefatto_dps_artefatto_pdr'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatura',
            name='is_new',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='nativo',
            name='is_new',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='viaggiatore',
            name='is_new',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
