# Generated by Django 6.0.8 on 2026-09-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0256_creatura_is_new_nativo_is_new_viaggiatore_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nativo',
            name='dream',
        ),
    ]
