# Generated by Django 6.0.8 on 2026-09-23 00:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0257_remove_nativo_dream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oggetto',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#808080ff', image_field=None, max_length=25, samples=None),
        ),
    ]
