# Generated by Django 6.0.8 on 2026-09-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0258_alter_oggetto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='oggetto',
            name='is_basic',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
